import { AppWrapper } from "@/components/provider/AppWrapper";
import "./globals.css";
import { Manrope } from "next/font/google";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <AppWrapper>{children}</AppWrapper>
        <div className="flex justify-center bg-[var(--primary-color)]">
        <div className="text-[var(--text-color)] text-[14px] md:text-[16px] text-center">
          <span className="">
            Built with Love by <span className="text-[red]">Olayinka_Dev</span>
          </span>{" "}
          <br />
          <span>Follow and give it a star on </span>
          <button>Github</button>
        </div>
        </div>
      </body>
    </html>
  );
}
